data: /home/shared-volume/data/sbi-training

remote_storage_config:
  key: tfl-training-participant@tfl-prod-ea3b.iam.gserviceaccount.com
  secret: "env:PARTICIPANT_BUCKET_READ_SECRET"
  bucket: tfl_trainings
  base_path: tfl_training_sbi
  provider: google_storage
